backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "public/assets" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets" # The src attribute for uploaded media will begin with /assets
collections:
  - name: "info"
    label: "Your information, interests, and background!"
    format: json
    extension: json
    files:
      - name: "myInfo"
        label: "Let's fill out your information."
        file: "src/copy/myInfo.json"
        fields:
          - {label: "Your current name", name: "myName", widget: "string"}
          - {label: "Your current About Me description.", name: "myDesc", widget: "markdown"}
          - label: "links to your online presence on other sites, if relevant."
            name: "myLinks"
            widget: "list"
            summary: '{{fields.myPlatform}}'
            allow_add: true
            add_to_top: true
            label_singular: "profile"
            fields:
              - {label: "What's the website or platform?", name: "myPlatform", widget: "string"}
              - {label: "Paste the permalink to your corresponding profile page on that website!", name: "myPlatformLink", widget: "string"}
          - name: "myCert"
            label: "Certifications"
            widget: "list"
            allow_add: true
            add_to_top: true
            label_singular: "Certification"
            fields: 
              - {name: "myCertItem", label: "What'd you earn?", widget: "string"}
      - name: "finds"
        label: "Interesting finds you want to share."
        file: "src/copy/myFinds.json"
        fields:
          - label: "finds"
            name: "myFinds"
            widget: "list"
            summary: '{{fields.myFindTitle}}, {{fields.myFindAuthor}}'
            allow_add: true
            add_to_top: true
            label_singular: "find"
            fields:
              - {label: "The Title", name: "myFindTitle", widget: "string"}
              - {label: "Author or Creator", name: "myFindAuthor", widget: "string"}
              - {label: "Publisher or Company", name: "myFindPublisher", widget: "string"}
              - {label: "Link to resource mentioned.", name: "myFindLink", widget: "string"}
  - name: "project"
    label: "Projects"
    folder: "src/p"
    media_folder: "../assets/p"
    create: true
    slug: "{{projsName}}"
    fields:
      - {label: "Project Name", name: "projsName", widget: "string"}
      - {label: "Medium, Discipline, or Type", name: "projsDscplne", widget: "string"}
      - {label: "Feature Image", name: "projsFtImg", widget: "image", media_folder: "../assets/p/{{projsName}}", public_folder: "../assets/p/{{projsName}}"}
      - {label: "Hero Image for project page.", name: "projsHeroImg", widget: "image", media_folder: "../assets/p/{{projsName}}", public_folder: "../assets/p/{{projsName}}"}
      - {label: "Prompt, challenge, or guiding question statement.", name: "projPrompt", widget: "string"}
      - {label: "Leading summary", name: "projDesc", widget: "markdown"}
      - label: "Project Multimedia"
        name: "media"
        widget: "object"
        collapsed: true
        media_folder: "../assets/p"
        fields:
          - {label: "Use multimedia on page", name: "use", widget: "boolean"}
          - {label: "Multimedia File", name: "file", widget: "file"}
      - label: "Project Images"
        name: "projImgs"
        widget: "list"
        summary: '{{fileName}} // {{fields.imageAlt}}'
        allow_add: true
        label_singular: "Project Image"
        fields:
          - {name: "image", label: "Image for project progress", widget: "image", media_folder: "../assets/p/{{projsName}}", public_folder: "../assets/p/{{projsName}}"}
          - {name: "imageAlt", label: "Image description for alt text", widget: "string"}
          - name: "position"
            label: "Position of outcome image on desktop"
            widget: "select"
            options: ["full","left","center","right"]
            default: ["full"]
      - {label: "Tag", name: "projTag", widget: "string"}
  - name: "extraimgs"
    label: "Extra Projects or Experiments"
    folder: "src/assets/extra"
    media_folder: "src/assets/extra"
    media_library:
      config:
        multiple: true
    fields:
      - {label: "Extra Project", name: "exImg", widget: "image"}
