backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "public/assets" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "saminfo"
    label: "Sami's Info"
    files: "src/copy/saminfo.md"
    fields:
      - {label: "Whatever your name is right now.", name: "myName", widget: "string"}
      - {label: "Tell them something about you!", name: "myDescription", widget: "markdown"}
      - label: "Your links to your online presence on other sites, if relevant."
        name: "myLinks"
        widget: "list"
        allow_add: true
        add-to-top: true
        label_singular: "Add a link"
        field:
          - {label: "What's the website or platform?", name: "myPlatform", widget: "string"}
          - {label: "Paste the permalink to your corresponding profile page on that website!", name: "smyPlatformLink", widget: "string"}
      - label: "Certifications so far."
        name: "certification"
        widget: "list"
        allow_add: true
        add-to-top: true
        label_singular: "Add a certification"
        field:
          - {label: "I've earned a...", name: "certItem", widget: "string"}

  - name: "project"
    label: "Projects"
    folder: "src/p"
    create: true
    slug: "{{projsName}}"
    fields:
      - {label: "Project Name", name: "projsName", widget: "string"}
      - {label: "Medium, Discipline, or Type", name: "projsDscplne", widget: "string"}
      - {label: "Feature Image", name: "projsFtImg", widget: "image"}
      - {label: "Hero Image for project page.", name: "projsHeroImg", widget: "image"}
      - {label: "Prompt, challenge, or guiding question statement.", name: "projPrompt", widget: "string"}
      - {label: "Leading summary", name: "projDesc", widget: "markdown"}
      - {label: "Tag", name: "projTag", widget: "string"}
  - name: "introimgs"
    label: "Intro Images"
    folder: "src/assets/introimgs"
    fields: 
      - {label: "Image 1 ", name: "introimg1", widget: "image"}
      - {label: "Image 2 ", name: "introimg2", widget: "image"}
      - {label: "Image 3 ", name: "introimg3", widget: "image"}
  - name: "finds"
    label: "Interesting Finds"
    folder: "src/assets/misc"
    create: true
    fields:
      - {label: "Misc Project Image", name: "miscimg", widget: "image"}
