backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "public/assets" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "myInfoCollection"
    label: "Your information and background!"
    file: "copy/saminfo.yml"
    fields:
      - { label: "Your current name", name: "myName", widget: "string"}
      - { label: "Your current About Me description.", name: "myDesc", widget: "markdown"}
      - label: "Your links to your online presence on other sites, if relevant."
        name: "myLinks"
        widget: "list"
        allow_add: true
        add_to_top: true
        label_singular: "Add a link to an online presence"
        fields:
          - label: "Online Presence"
            name: "myLinkPresence"
            widget: object
            fields:
              - {label: "What's the website or platform?", name: "myPlatform", widget: "string"}
              - {label: "Paste the permalink to your corresponding profile page on that website!", name: "myPlatformLink", widget: "string"}
      - name: "myCert"
        label: "Certifications"
        widget: "list"
        allow_add: true
        add_to_top: true
        label_singular: "Add a new certification"
        fields: 
          - {name: "myCertItem", label: "What'd you earn?", widget: "string"}
  - name: "project"
    label: "Projects"
    folder: "src/p"
    create: true
    slug: "{{projsName}}"
    fields:
      - {label: "Project Name", name: "projsName", widget: "string"}
      - {label: "Medium, Discipline, or Type", name: "projsDscplne", widget: "string"}
      - {label: "Feature Image", name: "projsFtImg", widget: "image"}
      - {label: "Hero Image for project page.", name: "projsHeroImg", widget: "image"}
      - {label: "Prompt, challenge, or guiding question statement.", name: "projPrompt", widget: "string"}
      - {label: "Leading summary", name: "projDesc", widget: "markdown"}
      - {label: "Tag", name: "projTag", widget: "string"}
  - name: "introimgs"
    label: "Intro Images"
    folder: "src/assets/introimgs"
    fields: 
      - {label: "Image 1 ", name: "introimg1", widget: "image"}
      - {label: "Image 2 ", name: "introimg2", widget: "image"}
      - {label: "Image 3 ", name: "introimg3", widget: "image"}
  - name: "finds"
    label: "Interesting Finds"
    folder: "src/assets/misc"
    create: true
    fields:
      - {label: "Misc Project Image", name: "miscimg", widget: "image"}
