backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "public/assets" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "project"
    label: "Projects"
    folder: "src/p"
    create: true
    slug: "{{projsName}}"
    fields:
      - {label: "Project Name", name: "projsName", widget: "string"}
      - {label: "Medium, Discipline, or Type", name: "projsDscplne", widget: "string"}
      - {label: "Feature Image", name: "projsFtImg", widget: "image"}
      - {label: "Hero Image for project page.", name: "projsHeroImg", widget: "image"}
      - {label: "Prompt, challenge, or guiding question statement.", name: "projPrompt", widget: "string"}
      - {label: "Leading summary", name: "projDesc", widget: "markdown"}
      - {label: "Tag", name: "projTag", widget: "string"}
  - name: "introimgs"
    label: "Intro Images"
    folder: "src/assets/introimgs"
    fields: 
      - {label: "Image 1 ", name: "introimg", widget: "image"}
      - {label: "Image 2 ", name: "introimg", widget: "image"}
      - {label: "Image 3 ", name: "introimg", widget: "image"}
  - name: "finds"
    label: "Interesting Finds"
    folder: "src/assets/misc"
    create: true
    fields:
      - {label: "Misc Project Image", name: "miscimg", widget: "image"}
